apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microblog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "microblog.name" . }}
    helm.sh/chart: {{ include "microblog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "microblog.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "microblog.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.mariadb.enabled }}
          - name: DATABASE_URL
            value: mysql+pymysql://{{ .Values.mariadb.db.user }}:{{ .Values.mariadb.db.password }}@{{ template "mariadb.fullname" . }}/{{ .Values.mariadb.db.name }}
          {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'until nslookup {{ template "mariadb.fullname" . }}; do echo waiting for {{ template "mariadb.fullname" . }}; sleep 2; done;']
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
